-- 2022년 1월의 도서 판매 기준
-- 저자, 카테고리 별 매출액
-- 저자 아이디 오름차순, 카테고리 내림차순
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, E.CATEGORY, E.TOTAL_SALES
FROM AUTHOR A
JOIN (SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
     FROM BOOK B
     JOIN BOOK_SALES S
     ON B.BOOK_ID = S.BOOK_ID
     WHERE SALES_DATE >= '2022-01-01'
     AND SALES_DATE < '2022-02-01'
     GROUP BY B.AUTHOR_ID, B.CATEGORY) E
ON A.AUTHOR_ID = E.AUTHOR_ID
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

