-- 년, 월, 성별 별로 상품을 구매한 회원수 집계
-- 결과는 년, 월, 성별 기준으로 오름차순

SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, I.GENDER, COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I
JOIN ONLINE_SALE S
ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), I.GENDER
ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), I.GENDER;