SELECT DISTINCT A.CAR_ID, IFNULL(AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT JOIN (
    SELECT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-10-16'
    AND START_DATE <= '2022-10-16') B
ON A.CAR_ID = B.CAR_ID
ORDER BY CAR_ID DESC;