SELECT CAR_ID,
    CASE 
        WHEN EXISTS (SELECT 1 
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
                    WHERE A.CAR_ID = B.CAR_ID
                    AND START_DATE <= '2022-10-16'
                    AND END_DATE >= '2022-10-16')
            THEN '대여중'
            ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;