-- 7월의 아이스크림 총 주문량 + 상반기 아이스크림 총 주문량이 큰 순서대로 상위 3개 맛 조회
SELECT J.FLAVOR
FROM JULY J
JOIN FIRST_HALF F
ON J.FLAVOR = F.FLAVOR 
GROUP BY J.FLAVOR 
ORDER BY SUM(J.TOTAL_ORDER + F.TOTAL_ORDER) DESC
LIMIT 3;