-- 보호소에서 몇 시에 입양이 가장 활발하게 일어나는지 알아보기
-- 시간대 순으로 정렬
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) > 8
AND HOUR(DATETIME) < 20
GROUP BY HOUR(DATETIME)
ORDER BY HOUR;