-- 분화된 연도, 분화된 연도별 대장균 크기의 편차, 대장균 ID

SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, 
    (SELECT MAX(SIZE_OF_COLONY)
    FROM ECOLI_DATA
    WHERE YEAR(DIFFERENTIATION_DATE) = YEAR(D.DIFFERENTIATION_DATE)) 
    - D.SIZE_OF_COLONY AS YEAR_DEV, D.ID
FROM ECOLI_DATA D
ORDER BY YEAR ASC, YEAR_DEV ASC;