-- 물고기 종류 별로 가장 큰 물고기 ID, 물고기 이름, 길이
SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO F
JOIN FISH_NAME_INFO N
ON F.FISH_TYPE = N.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
      FROM FISH_INFO
     GROUP BY FISH_TYPE) M
ON F.FISH_TYPE = M.FISH_TYPE
WHERE F.LENGTH = M.MAX_LEN
ORDER BY F.ID;