-- 평균 길이가 33cm 이상인 물고기
-- 종류 별로 잡은 수, 최대 길이, 물고기 종류
SELECT COUNT(*) AS FISH_COUNT,
MAX(LENGTH) AS MAX_LENGTH,
FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) >= 33
ORDER BY FISH_TYPE ASC;